//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CypressGUI.rc
//
#define IDOK2                           5
#define IDDEFAULT                       5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_DIALOGWITHTWO               101
#define IDD_CYPRESSGUI_DIALOG           102
#define IDD_ONECONTROL                  103
#define IDD_CIRCUITPAGE1                104
#define IDD_CIRCUITPAGE2                105
#define IDD_CIRCUITPAGE3                106
#define IDR_MAINFRAME                   128
#define IDB_FI                          133
#define IDB_SCHEME1                     134
#define IDB_DEVICE                      135
#define IDB_AIR                         139
#define IDB_INPUT_VALUES                140
#define IDB_PARAMETERS                  141
#define IDB_DEVICE_CONTROL              144
#define IDB_SCHEME                      145
#define IDB_RESULT                      146
#define IDB_HODOGRAPH                   147
#define IDB_RUNCONTROL                  148
#define IDB_GENERATED_CIRCUIT           149
#define IDB_ELEMENT_VALUES              150
#define IDB_TUPPER                      151
#define IDB_UOUT                        152
#define IDB_UIN                         153
#define IDB_F                           154
#define IDB_TLOWER                      155
#define IDB_RE                          156
#define IDB_IM                          157
#define IDB_Z                           157
#define IDB_F1                          158
#define IDB_F2                          159
#define IDR_MENU                        161
#define IDD_LOGDLG                      162
#define IDD_RANGE_DLG                   163
#define IDD_SETTINGS_DLG                164
#define IDB_GAS                         166
#define IDB_FLOW                        169
#define IDB_MIX                         170
#define IDB_DEVICE_2                    171
#define IDC_TABCIRCUIT                  1000
#define IDC_BUTTONSTART                 1001
#define IDC_BUTTONSTOP                  1002
#define IDC_TABFREQ                     1003
#define IDC_SLIDERTEMPERATURE           1004
#define IDC_SLIDERVOLTAGEEXIT           1005
#define IDC_SLIDERGAS                   1006
#define IDC_SLIDERF                     1006
#define IDC_SLIDERAIR                   1007
#define IDC_SLIDERMIX                   1008
#define IDC_SLIDERFLOW                  1009
#define IDC_EDITTEMPERATURE             1010
#define IDC_EDITVOLTAGE                 1011
#define IDC_SLIDERF1                    1011
#define IDC_EDITFREQ                    1012
#define IDC_SLIDERF2                    1012
#define IDC_INDICATOR_TEMP              1013
#define IDC_INDICATOR_VOLTAGE           1014
#define IDC_INDICATOR_GAS               1015
#define IDC_INDICATOR_F1                1015
#define IDC_INDICATOR_AIR               1016
#define IDC_INDICATOR_F2                1016
#define IDC_INDICATOR_MIX               1017
#define IDC_INDICATOR_F                 1017
#define IDC_INDICATOR_FLOW              1018
#define IDC_BUTTONSTART2                1019
#define IDC_BUTTONSTART3                1020
#define IDC_BUTTONSTART4                1021
#define IDC_BUTTONCONNECT               1022
#define IDC_BUTTONSTART5                1023
#define IDC_EDIT_Z                      1024
#define IDC_EDIT_FI                     1025
#define IDC_EDITFREQ2                   1026
#define IDC_EDIT_R0                     1026
#define IDC_EDITFREQ3                   1027
#define IDC_EDIT_R1                     1027
#define IDC_EDITFREQ4                   1028
#define IDC_EDIT_C0                     1028
#define IDC_EDITFREQ5                   1029
#define IDC_EDIT_C1                     1029
#define IDC_EDITFREQ6                   1030
#define IDC_EDITFREQ7                   1031
#define IDC_EDITFREQ8                   1032
#define IDC_EDITFREQ9                   1033
#define IDC_EDIT_HODOGRAPH_FREQUENCY    1034
#define IDC_LOGLIST                     1035
#define IDC_EDIT1                       1036
#define IDC_STEP                        1036
#define IDC_LIST_RANGES                 1037
#define IDC_EDIT2                       1038
#define IDC_REMOVE_BTN                  1039
#define IDC_EDIT3                       1040
#define IDC_ADD_BTN                     1041
#define IDC_EDIT4                       1041
#define IDC_EDIT5                       1042
#define IDC_EDIT6                       1043
#define IDC_EDIT7                       1044
#define IDC_EDIT8                       1045
#define IDC_EDIT9                       1046
#define IDC_EDIT10                      1047
#define IDC_EDIT11                      1048
#define IDC_EDIT12                      1049
#define IDC_COMBO1                      1050
#define IDC_EDIT13                      1051
#define IDC_EDIT14                      1052
#define IDC_EDIT15                      1053
#define ID_APPLICATION_EXIT             32776
#define ID_SAVE_PLOT                    32777
#define ID_SAVE_APPROXIMATE             32778
#define ID_SAVE_HODOGRAPH               32779
#define ID_DATA_SAVE                    32780
#define ID_                             32781
#define ID_DATA_SAVE32782               32782
#define ID_DATA_PLOTFILE                32783
#define ID_CHART_CLEAR                  32784
#define ID_CHART_STOP                   32785
#define ID_CHART_START                  32786
#define ID_CHART_HODOHRAPH              32787
#define ID_CHART_PLOTFILE               32788
#define ID_CHART_PLOTCURRENTDATA        32789
#define ID_LOG_SHOW                     32790
#define ID_LOG_HIDE                     32791
#define ID_DATA_MERGE                   32792
#define ID_LOG_CLEAR                    32793
#define ID_APPLICATION_SETTINGS         32794
#define ID_Menu                         32795
#define ID_CHART_MODE                   32796
#define ID_MODE_SHOWPHASE               32797
#define ID_MODE_SHOWHODOGRAPH           32798
#define ID_CHART_SHOWHODOHRAPH          32799
#define ID_CHART_SHOWPHASE              32800
#define ID_DATA_CLEAR                   32801
#define ID_DATA_SAVEHODOGRAPH           32802
#define ID_CHART_SAVEHODOGRAPH          32803
#define ID_CHART_APPROXIMATEHODOHRAPH   32804
#define ID_CHART_STARTCHARTFROM         32805
#define ID_CHART_SHOWNEGATIVEPART       32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
