#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define CMN_NAMESPACE_NAME
#define CMN_NAMESPACE_BEGIN namespace CMN_NAMESPACE_NAME{
#define CMN_NAMESPACE_END }


#endif // CONFIG_H_INCLUDED
